[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200